services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: wpp_bot_api
    ports:
      - '5000:5000'
    volumes:
      - .:/app
      - ./chroma_data:/app/chroma_data
    depends_on:
      - waha
      
  db:
    image: postgres:latest
    container_name:   
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wpp_bot
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: